<?php
$lang = array(
'postinstall' => 'Post Install Message.',
'postuninstall' => '',
'really_uninstall' => 'Really? Are you sure
you want to unsinstall this fine module?',
'uninstalled' => 'Module Uninstalled.',
'installed' => 'Module version %s installed.',
'upgraded' => 'Module upgraded to version %s.',
// 'moddescription' => 'This module is generated by M&C Factory',

'tab_items' => 'Items',
'tab_templates' => 'Templates',
'tab_options' => 'Options',
'tab_help' => 'Help',

'error' => 'Error!',
// 'admin_title' => 'Companies Admin Panel',
'admindescription' => 'This module helps you to manage specific items',
'titleTemplate' => 'Title',
'codeTemplate' => 'Template',
'accessdenied' => 'Access Denied. Please check your permissions.',
'postinstall' => 'Be sure to set "Manage Companies" permissions to use this module!',

'submit' => 'Submit',
'apply' => 'Apply',
'cancel' => 'Cancel',
'restorelist' => 'Restore list',
'restoredetails' => 'Restore details',
'publish' => 'Publish',
'unpublish' => 'Unpublish',


'add template' => 'Add template',
'select one' => 'Select one',
'form_template' => 'Template',
'form_restore_template_from' => 'Restore template from',
'form_code' => 'Code',
'form_default_template_for' => 'Default template for',
'default template for' => 'default template for "%s" action',

// user form
'you do not have the permission to use this action' => 'You do not have the permission to use this action',
'form_user_id' => 'User id',
'form_title' => 'Title',
'item posted' => 'Item successfully posted',

'save' => 'Save',
'save_add' => 'Save &amp; add a new item',
'save_continue' => 'Save & continue editing',
'delete' => 'Delete',
'add_item' => 'Add item',
'add_item_for' => 'Add item for [%s]',
'edit_item' => 'Edit item',
'update_objects' => 'Update objects',
'preview_s' => 'Preview [%s]',

'form_parent_id' => 'Parent',
'form_order_by' => 'Order by',
'form_order_by_direction' => 'Order direction',
'form_items_per_page' => 'Items per page',
'form_date_format' => 'Date format',
'form_default_page' => 'Default page',
'form_show_parent' => 'Show parents dropdown',
'form_show_parent_first_level' => 'Show parents first level only',
'form_save_add' => 'Show Save &amp; add button',
'form_index_content' => 'Index content',
'form_use_cmon' => 'Use Campaign Monitor',
'form_cmon_from' => 'Campaign Monitor From',
'form_cmon_from_email' => 'Campaign Monitor From email',
'form_cmon_template' => 'Campaign Monitor template',
'form_cmon_template_plain' => 'Campaign Monitor template (plain text version)',
'form_cmon_default_page' => 'Default page for Campaign Monitor HTML',
'form_use_twitter' => 'Use Twitter',
'form_twitter_template' => 'Twitter template (available fields: {$title}, {$url})',
'module_options' => 'Options',


'form_remote_gallery' => 'Remote gallery URL',
'form_enable_api' => 'Enable API',

'select_one' => 'Select one',
'export' => 'Export',
'serialized_datas' => 'PHP Serialized array',
'download' => 'Download',

'form_uploads_path' => 'Uploads path',
'form_module' => 'Module',
'form_select_module_for_migration' => 'Select the module you want to migrate',
'form_fields' => 'Fields',
'form_select_fields_to_populate' => 'Select the module\'s fields you want to populate',
'Continue' => 'Continue',

'changelog' => '<ul>
<li>Version 0.0.1 - 1 November 2012. Initial Release.</li>
</ul>',
'help' => '
<h3>Help</h3>
<p>To call a gallery, use {MCMedias collection_id="Your Collection ID" template="Your template"}. Template is not mandatory. You can also pass a list of collections IDs with param collection_ids and the collections ids separated by coma. You can pass params and recuperate them via {$mcmedias_params}</p>
<h4>Thumbnails</h4>
<p>To create thumbnails, use {MCMedias action="thumbnail" width=150 height=150 file=$file->getRelativePath()} which will create them in the cache directory.</p>
<p>You can also use any pictures inside the /uploads/ directory. Your filename should begin with "/uploads/"</p>
<p>You can use the shorter version: {Thumbnail}</p>
<p><u>Options</u></p>
<ul>
  <li>width</li>
  <li>height</li>
  <li>size: set both width and height</li>
  <li>mode (only "default" for the moment)</li>
</ul>
<h4>Cover</h4>
<p>You can get the thumbnail of the cover of a file with {MCMedias action="thumbnail" width=150 height=150}. It uses the same parameters as Thumbnails.</p>
<h4>Direct thumbnailing</h4>
<p>If you need to do a "direct" thumbnailing, you can use the URL \'/thumbnail/path_to_your_file.ext\' directly in the SRC attribute of your image. You can also add the desire sizes: \'/thumbnail/150/path_to_your_file.ext\' will create a 150x150 thumbnail. \'/thumbnail/300/200/path_to_your_file.ext\' will create a thumbnail 300px width and 200px height. Those url will directly delivers you the image (through a redirection).</p>
<h4>Divers</h4>
<p>List of functions on a MCFile entry</p>
<ul>
  <li>getFilename()</li>
  <li>getUrl()</li>
  <li>getFileSize()</li>
  <li>getFileExtension()</li>
  <li>getFileIcon()</li>
</ul>
<h3>Support</h3>
<p>As per the GPL, this software is provided as-is. Please read the text of the license for the full disclaimer.</p>
<h3>Copyright and License</h3>
<p>Copyright &copy; 2010, Jean-Christophe Cuvelier <a href="mailto:jcc@morris-chapman.com">&lt;jcc@morris-chapman.com&gt;</a> - Morris &amp; Chapman. All Rights Are Reserved.</p>
<p>This module has been released under the <a href="http://www.gnu.org/licenses/licenses.html#GPL">GNU Public License</a>. You must agree to this license before using the module.</p>'
);